# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

# Uncomment this line if you're using Swift
use_frameworks!

target 'Country' do

pod 'SwiftyUserDefaults'
pod 'SwiftKeychainWrapper'
pod 'IQKeyboardManager'
pod 'SQLite.swift'
pod 'AsyncSwift'
pod 'JLToast'
pod 'ObjectMapper'
pod 'Alamofire'
pod 'SwiftyJSON'
pod 'AlamofireSwiftyJSON'
pod 'pop'
pod 'EAIntroView'
pod 'MaterialKit'
pod 'RNLoadingButton'
pod 'SWRevealViewController'
pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Messaging'
pod 'OneSignal'

end

